version: "3.9"

services:
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - lb-entrevista-app-native-osx-sync:/project:nocopy
      - lb-entrevista-bundle-native-osx-sync:/.bundle:nocopy
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
      RAILS_ENV: development
      DATABASE_HOST: host.docker.internal

  test:
    build: .
    command: /bin/sh -c "bundle exec rails db:drop && bundle exec rails db:create && bundle exec rails db:schema:load"
    volumes:
      - lb-entrevista-app-native-osx-sync:/project:nocopy
      - lb-entrevista-bundle-native-osx-sync:/.bundle:nocopy
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
      RAILS_ENV: test
      DATABASE_HOST: host.docker.internal

volumes:
  lb-entrevista-app-native-osx-sync:
    external: true
  lb-entrevista-bundle-native-osx-sync:
    external: true